apiVersion: v1
kind: Service
metadata:
  name: srv
spec:
  type: NodePort
  selector:
    app: srv
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv
spec:
  selector:
    matchLabels:
      app: srv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: srv
    spec:
      containers:
      # - image: outlier11111001000/srv:0.0.1.debug
      - image: outlier11111001000/srv:0.0.1
        name: srv
        env:
        - name: MYSQL_ADDRESS
          value: 172.17.0.8:3306
        - name: MYSQL_NET
          value: tcp
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: my-secret-pw
        - name: MYSQL_DBNAME
          value: dev
        ports:
        - containerPort: 80
          name: srv
